server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TuralNazarov/online-shop-microservices
          default-label: main
          clone-on-start: true
  application:
    name: config-server
